sudo: false
language: rust

addons:
  ssh_known_hosts: 'petition.bewegung.jetzt'

before_script:
  - cargo install cobalt-bin
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cobalt build

before_deploy:
- openssl aes-256-cbc -K $encrypted_5ba0802f0861_key -iv $encrypted_5ba0802f0861_iv
  -in scripts/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  script: scp -R build root@petition.bewegung.jetzt:/var/dib/petition/build
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
