version: '2'
services:
  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=petition.bewegung.jetzt
      - LETSENCRYPT_DOMAIN=petition.bewegung.jetzt
      - LETSENCRYPT_EMAIL=tech@bewegung.jetzt
      - NGINX_HOST=petition.bewegung.jetzt
      - NGINX_PORT=80
    volumes:
      - ./build:/usr/share/nginx/html:ro
    expose:
      - 80
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
